"""
Small pixel-art helpers for the Crystal Caves-style game.

The goal is not to copy the original assets. Instead, this module gives the
game a deliberately authored EGA/DOS sprite pipeline so visual work can move
past ad-hoc pygame primitives.
"""

from __future__ import annotations

from typing import Dict, Tuple

import pygame

Color = Tuple[int, int, int]


EGA: Dict[str, Color] = {
    ".": (0, 0, 0),
    "K": (0, 0, 0),
    "W": (255, 255, 255),
    "w": (210, 210, 220),
    "Y": (255, 224, 64),
    "O": (255, 156, 40),
    "S": (255, 190, 132),
    "P": (255, 72, 172),
    "B": (58, 82, 255),
    "R": (255, 64, 52),
    "G": (64, 236, 80),
    "g": (0, 130, 34),
    "C": (88, 232, 255),
    "c": (28, 120, 196),
    "M": (176, 176, 190),
    "m": (86, 86, 104),
    "V": (190, 70, 210),
    "v": (112, 32, 136),
    "A": (255, 78, 64),
    "L": (255, 240, 92),
    "N": (150, 82, 32),
    "n": (92, 48, 18),
    "D": (0, 0, 132),
    "d": (36, 70, 204),
    "E": (98, 255, 98),
    "e": (0, 94, 42),
    "T": (255, 122, 48),
    "t": (148, 0, 0),
    "Z": (104, 255, 104),
    "z": (0, 82, 16),
}


SPRITES: Dict[str, Tuple[str, ...]] = {
    "mylo_idle": (
        "....KKKK....",
        "...KYYYYK...",
        "..KYYYYYYK..",
        "..KOOOYYYK..",
        "...KSSSSK...",
        "...KSKSSK...",
        "..KSPPPPSK..",
        ".KPPPPPPPPK.",
        ".KPPBBPPPPK.",
        "..KBBBBBBK..",
        "..KBWBBWBK..",
        "..KBBBBBBK..",
        "..KRK..KRK..",
        ".KRRK.KRRK..",
        ".KRRK.KRRK..",
        "..KK...KK...",
    ),
    "mylo_walk_1": (
        "....KKKK....",
        "...KYYYYK...",
        "..KYYYYYYK..",
        "..KOOOYYYK..",
        "...KSSSSK...",
        "...KSKSSK...",
        "..KSPPPPSK..",
        ".KPPPPPPPPK.",
        ".KPPBBPPPPK.",
        "..KBBBBBBK..",
        "..KBWBBWBK..",
        "..KBBBBBBK..",
        ".KRRK.KRK...",
        "KRRK..KRRK..",
        ".KK....KRRK.",
        "........KK..",
    ),
    "mylo_walk_2": (
        "....KKKK....",
        "...KYYYYK...",
        "..KYYYYYYK..",
        "..KOOOYYYK..",
        "...KSSSSK...",
        "...KSKSSK...",
        "..KSPPPPSK..",
        ".KPPPPPPPPK.",
        ".KPPBBPPPPK.",
        "..KBBBBBBK..",
        "..KBWBBWBK..",
        "..KBBBBBBK..",
        "...KRK.KRRK.",
        "..KRRK..KRRK",
        ".KRRK....KK.",
        "..KK........",
    ),
    "mylo_jump": (
        "....KKKK....",
        "...KYYYYK...",
        "..KYYYYYYK..",
        "..KOOOYYYK..",
        "...KSSSSK...",
        "...KSKSSK...",
        "..KSPPPPSK..",
        ".KPPPPPPPPK.",
        ".KPPBBPPPPK.",
        "..KBBBBBBK..",
        "..KBWBBWBK..",
        ".KRRBBBBRRK.",
        "KRRK....KRRK",
        ".KK......KK.",
        "............",
        "............",
    ),
    "mylo_shoot": (
        "....KKKK....",
        "...KYYYYK...",
        "..KYYYYYYK..",
        "..KOOOYYYK..",
        "...KSSSSK...",
        "...KSKSSK...",
        "..KSPPPPSK..",
        ".KPPPPPPPPK.",
        ".KPPBBPPPPKKKK",
        "..KBBBBBBKMMMMK",
        "..KBWBBWBKwwLLK",
        "..KBBBBBBKKKKK.",
        "..KRK..KRK.....",
        ".KRRK.KRRK.....",
        ".KRRK.KRRK.....",
        "..KK...KK......",
    ),
    "mylo_hurt": (
        "....KKKK....",
        "...KYYYYK...",
        "..KYYYYYYK..",
        "..KOOOYYYK..",
        "...KSSSSK...",
        "...KAKSAK...",
        "..KSPPPPSK..",
        ".KPPPPPPPPK.",
        ".KPPBBPPPPK.",
        "..KBBBBBBK..",
        ".KRBWBBWBK..",
        "KRRKBBBBK...",
        ".KKR..KRK...",
        "......KRRK..",
        ".......KK...",
        "............",
    ),
    "raygun": (
        "................",
        "................",
        "................",
        "................",
        "....wwwwwwwww...",
        "...wMMMMMMMMMw..",
        "..wMwwwwwwwwMw..",
        "..wMwwLLLwwwMwL.",
        "...wMMMMMMMMMw..",
        "....wwwwwMMw....",
        "........wMMw....",
        ".........ww.....",
        "................",
        "................",
        "................",
        "................",
    ),
    "crystal_blue": (
        ".......WW.......",
        "......WCCW......",
        ".....WCCCCW.....",
        "....WCCCCCCW....",
        "...WCCWWCCCCW...",
        "..WCCCCWWCCCCW..",
        ".WCCCCCCCCCCCCW.",
        "WCCCCCCCCCCCCCCW",
        "WCCCCCCCCCCCCCCW",
        ".WCCCCCccCCCCCW.",
        "..WCCCCccCCCCW..",
        "...WCCCccCCCW...",
        "....WCCccCCW....",
        ".....WCccCW.....",
        "......WccW......",
        ".......WW.......",
    ),
    "crystal_green": (
        ".......WW.......",
        "......WEEW......",
        ".....WEEEEW.....",
        "....WEEEEEEW....",
        "...WEEWWEEEEW...",
        "..WEEEEWWEEEEW..",
        ".WEEEEEEEEEEEEW.",
        "WEEEEEEEEEEEEEEW",
        "WEEEEEEEEEEEEEEW",
        ".WEEEEEeeEEEEEW.",
        "..WEEEEeeEEEEW..",
        "...WEEEeeEEEW...",
        "....WEEeeEEW....",
        ".....WEeeEW.....",
        "......WeeW......",
        ".......WW.......",
    ),
    "crystal_yellow": (
        ".......WW.......",
        "......WYYW......",
        ".....WYYYYW.....",
        "....WYYYYYYW....",
        "...WYYWWYYYYW...",
        "..WYYYYWWYYYYW..",
        ".WYYYYYYYYYYYYW.",
        "WYYYYYYYYYYYYYYW",
        "WYYYYYYYYYYYYYYW",
        ".WYYYYYOOYYYYYW.",
        "..WYYYYOOYYYYW..",
        "...WYYYOOYYYW...",
        "....WYYOOYYW....",
        ".....WYOOYW.....",
        "......WOOW......",
        ".......WW.......",
    ),
    "crystal_red": (
        ".......WW.......",
        "......WAAW......",
        ".....WAAAAW.....",
        "....WAAAAAAW....",
        "...WAAWWAAAAW...",
        "..WAAAAWWAAAAW..",
        ".WAAAAAAAAAAAAW.",
        "WAAAAAAAAAAAAAAW",
        "WAAAAAAAAAAAAAAW",
        ".WAAAAAttAAAAAW.",
        "..WAAAAtAAAAW..",
        "...WAAAttAAW....",
        "....WAAtAAW.....",
        ".....WAttW......",
        "......WttW......",
        ".......WW.......",
    ),
    "ammo": (
        "................",
        "................",
        "...KKKKKKKKKK...",
        "..KwwwwwwwwwwK..",
        ".KwwWWwwwwwwwwK.",
        ".KwwWwYYYYwwwwK.",
        ".KwwwwYYYYYYYYK.",
        ".KwwwYYYYYYYYYK.",
        ".KwwwYYYYYYYYYK.",
        ".KwwwwYYYYYYYYK.",
        ".KwwwwwwwwwwwwK.",
        "..KwwwwwwwwwwK..",
        "...KKKKKKKKKK...",
        "................",
        "................",
        "................",
    ),
    "air_tank": (
        ".....KKKKKK.....",
        "....KMMMMMMK....",
        "....KwwwwwwK....",
        "...KCCCCCCCCK...",
        "...KCWWCCCCCK...",
        "...KCWWCCCCCK...",
        "...KCWWCCCCCK...",
        "...KCWWCCCCCK...",
        "...KCCCCCCCCK...",
        "...KCCCCCCCCK...",
        "...KCCCCCCCCK...",
        "...KCCCCCCCCK...",
        "...KCCCCCCCCK...",
        "....KCCCCCCK....",
        ".....KKKKKK.....",
        "................",
    ),
    "power": (
        "..KKKKKKKKKKKK..",
        ".KAAAAAAAAAAAAK.",
        "KAAWWAAAAAAWWAAK",
        "KAAWWAAAAAAWWAAK",
        "KAAAAAAAAAAAAAAK",
        "KAAAAAWWWWAAAAAK",
        "KAAAAWWYYWWAAAAK",
        "KAAAAWYYYYWAAAAK",
        "KAAAAWWYYWWAAAAK",
        "KAAAAAWWWWAAAAAK",
        "KAAAAAAAAAAAAAAK",
        "KAAWWAAAAAAWWAAK",
        "KAAWWAAAAAAWWAAK",
        ".KAAAAAAAAAAAAK.",
        "..KKKKKKKKKKKK..",
        "................",
    ),
    "crawler": (
        "................",
        "................",
        "....KKKKKKKK....",
        "..KKGGGGGGGGKK..",
        ".KGGZZGGGGZZGGK.",
        "KGGGGGGGGGGGGGGK",
        "KGGGggGGGGggGGGK",
        ".KGGggggggggGGK.",
        "..KGGGGGGGGGGK..",
        "...KgK....KgK...",
        "..KggK....KggK..",
        ".KKK......KKK...",
    ),
    "flyer": (
        "................",
        "..KKK......KKK..",
        ".KVVVK....KVVVK.",
        "KVVVVVK..KVVVVVK",
        "KVVVVVVKKVVVVVVK",
        ".KVVVVGGGGVVVVK.",
        "..KGGGGGGGGGGK..",
        "..KGGWWGGWWGGK..",
        "...KGGGGGGGGK...",
        "....KAAggAAK....",
        ".....KKKKKK.....",
        "................",
    ),
    "switch_off": (
        "................",
        "................",
        "......KK........",
        ".....KAAK.......",
        "....KAAK........",
        "...KAAK.........",
        "...KKK..........",
        ".....K..........",
        ".....K..........",
        "...KKKKKKKK.....",
        "..KMMMMMMMMK....",
        "..KMMMMMMMMK....",
        "...KKKKKKKK.....",
        "................",
        "................",
        "................",
    ),
    "switch_on": (
        "................",
        "................",
        ".........KK.....",
        "........KEEK....",
        ".......KEEK.....",
        "......KEEK......",
        ".....KKK........",
        ".....K..........",
        ".....K..........",
        "...KKKKKKKK.....",
        "..KMMMMMMMMK....",
        "..KMMMMMMMMK....",
        "...KKKKKKKK.....",
        "................",
        "................",
        "................",
    ),
    "door_locked": (
        "KKKKKKKKKKKKKKKK",
        "KMMMMMMMMMMMMMMK",
        "KMKAAAAAAAAAAKMK",
        "KMKAttttttAAAKMK",
        "KMKAAtKKtAAAAKMK",
        "KMKAAKwwKAAAAKMK",
        "KMKAAKwwKAAAAKMK",
        "KMKAAKwwKAAAAKMK",
        "KMKAAKwwKAAAAKMK",
        "KMKAAKwwKAAAAKMK",
        "KMKAAKwwKAAAAKMK",
        "KMKAAAAAAAAAAKMK",
        "KMKAAAAAAAAAAKMK",
        "KMMMMMMMMMMMMMMK",
        "KKKKKKKKKKKKKKKK",
        "................",
    ),
    "door_open": (
        "KKKKKKKKKKKKKKKK",
        "KMMMMMMMMMMMMMMK",
        "KMKEEEEEEEEEEKMK",
        "KMKEEEEKKKKEEKMK",
        "KMKEEEKKKKKEEKMK",
        "KMKEEKK..KKEEKMK",
        "KMKEEK....KEEKMK",
        "KMKEEK....KEEKMK",
        "KMKEEK....KEEKMK",
        "KMKEEKK..KKEEKMK",
        "KMKEEEKKKKEEEKMK",
        "KMKEEEEEEEEEEKMK",
        "KMKEEEEEEEEEEKMK",
        "KMMMMMMMMMMMMMMK",
        "KKKKKKKKKKKKKKKK",
        "................",
    ),
    "spikes": (
        "................",
        "................",
        "................",
        ".......WW.......",
        "...WW..WW..WW...",
        "..WWWWWWWWWWWW..",
        ".WWWWWWWWWWWWWW.",
        "WWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWW",
        "AAAWWAAAWWAAAWWA",
        "AAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAA",
        "................",
        "................",
        "................",
        "................",
    ),
    "acid": (
        "................",
        "................",
        "................",
        "TT..TT..TT..TT..",
        "LLLLLLLLLLLLLLLL",
        "TTTTTTTTTTTTTTTT",
        "ttTTttTTttTTttTT",
        "tttttttttttttttt",
        "tttttttttttttttt",
        "tttttttttttttttt",
        "tttttttttttttttt",
        "tttttttttttttttt",
        "................",
        "................",
        "................",
        "................",
    ),
    "crate": (
        "................",
        "..KKKKKKKKKKKK..",
        ".KNNNNNNNNNNNNK.",
        ".KNNNnnNNnnNNNK.",
        ".KNnNNnNNnNNnNK.",
        ".KNNnNNnnNNnNNK.",
        ".KNNNnnNNnnNNNK.",
        ".KNNNNNNNNNNNNK.",
        ".KNNnnNNNNnnNNK.",
        ".KNnNNnNNnNNnNK.",
        ".KNNnNNnnNNnNNK.",
        ".KNNNnnNNnnNNNK.",
        ".KNNNNNNNNNNNNK.",
        "..KKKKKKKKKKKK..",
        "................",
        "................",
    ),
    "lamp": (
        "................",
        ".......KK.......",
        "......KwwK......",
        "......KwwK......",
        ".....KMMMMK.....",
        "....KMMLLMMK....",
        "....KMLLLLMK....",
        "....KMMLLMMK....",
        ".....KMMMMK.....",
        "......KMMK......",
        "......KMMK......",
        ".....KMMMMK.....",
        "....KMMMMMMK....",
        ".....KKKKKK.....",
        "................",
        "................",
    ),
    "pickaxe": (
        "................",
        "................",
        "...KKKKKKKKKK...",
        "..KwwwwwwwwwwK..",
        ".KwwwwKwwwwww...",
        "....KNNK........",
        "...KNNK.........",
        "...KNNK.........",
        "..KNNK..........",
        "..KNNK..........",
        ".KNNK...........",
        ".KNNK...........",
        "KNNK............",
        "KKK.............",
        "................",
        "................",
    ),
    "walking_rock": (
        "................",
        "................",
        ".....KKKKK......",
        "...KKddddKK.....",
        "..KddddddddK....",
        ".KddwwddwwddK...",
        ".KddddddddddK...",
        "KdddDddddDdddK..",
        "KddddddddddddK..",
        ".KddDddddDddK...",
        "..KddddddddK....",
        "...KKdKKdKK.....",
        "..KK..KK..KK....",
        ".KK....KK..KK...",
        "................",
        "................",
    ),
    "eye_flyer": (
        "................",
        "..KKK......KKK..",
        ".KVVVK....KVVVK.",
        "KVVVVVK..KVVVVVK",
        "KVVVVVVKKVVVVVVK",
        ".KVVVVAAAAAVVVK.",
        "..KAAAWWAAAAK...",
        "..KAAWKKWAAAK...",
        "...KAAWWAAAK....",
        "....KAAAAAK.....",
        ".....KttK.......",
        "......KK........",
        "................",
        "................",
        "................",
        "................",
    ),
    "slug_enemy": (
        "................",
        "................",
        "................",
        "....KKKKK.......",
        "..KKNNNNNKK.....",
        ".KNNNNNNNNNK....",
        "KNNNWWNNWWNNK...",
        "KNNNNNNNNNNNNK..",
        ".KNNttttttNNK...",
        "..KNNNNNNNNK....",
        "...KKNNNNKK.....",
        ".....KKKK.......",
        "................",
        "................",
        "................",
        "................",
    ),
    "bat_enemy": (
        "................",
        "..KKK......KKK..",
        ".KvvvK....KvvvK.",
        "KvvvvK....KvvvvK",
        "KvvvvvK..KvvvvvK",
        ".KvvvVVKKVVvvvK.",
        "..KVVAAAAAAVVK..",
        "...KAAWWAAAK....",
        "....KAAKKAAK....",
        ".....KAAAAK.....",
        "......KttK......",
        ".......KK.......",
        "................",
        "................",
        "................",
        "................",
    ),
    "eye_turret": (
        "................",
        ".....KKKKKK.....",
        "...KKMMMMMMKK...",
        "..KMMCCCCCCMMK..",
        ".KMMCCWWCCCCCMM.",
        ".KMMCCWKKWCCCMM.",
        "..KMMCCWWCCMMK..",
        "...KKMMMMMMKK...",
        ".....KKMMKK.....",
        "......KMMK......",
        ".....KMMMMK.....",
        "....KMMMMMMK....",
        "...KMMmmmmMMK...",
        "..KKKKKKKKKKKK..",
        "................",
        "................",
    ),
    "clear_block": (
        "KKKKKKKKKKKKKKKK",
        "KCCCCCCCCCCCCCCK",
        "KCWWCCCCCCCCCCCK",
        "KCWCCCCCCCCCCCCK",
        "KCCCCCCCCCCCCCCK",
        "KCCCCCCCCCCCCCCK",
        "KCCCCCCCCCCCCCCK",
        "KCCCCCCCCCCCCCCK",
        "KCCCCCCCCCCCCCCK",
        "KCCCCCCCCCCCCCCK",
        "KCCCCCCCCCCCCCCK",
        "KCCCCCCCCCCCCCCK",
        "KCCCCCCCCCCCWWCK",
        "KCCCCCCCCCCCCWCK",
        "KCCCCCCCCCCCCCCK",
        "KKKKKKKKKKKKKKKK",
    ),
    "generator": (
        "KKKKKKKKKKKKKKKK",
        "KMMMMMMMMMMMMMMK",
        "KMmmmmMMMMmmmmMK",
        "KMMCCMMMMYYMMCMK",
        "KMMCCMMMMYYMMCMK",
        "KMmmmmMMMMmmmmMK",
        "KMMMMKKKKMMMMMMK",
        "KMEEKKwwKKEEEMMK",
        "KMEEKKwwKKEEEMMK",
        "KMMMMKKKKMMMMMMK",
        "KMMRRMMMMGGMmMMK",
        "KMMRRMMMMGGMMmMK",
        "KMmmmmMMMMmmmmMK",
        "KMMMMMMMMMMMMMMK",
        "KKKKKKKKKKKKKKKK",
        "................",
    ),
    "terminal": (
        "................",
        "..KKKKKKKKKKKK..",
        ".KMMMMMMMMMMMMK.",
        ".KMMCCCCCCCCMMK.",
        ".KMMCWWCCCCMMMK.",
        ".KMMCCCCCCCCMMK.",
        ".KMMMMMMMMMMMMK.",
        "..KKKKKKKKKKKK..",
        "....KMMMMMMK....",
        "...KMMMMMMMMK...",
        "..KMMMMMMMMMMK..",
        "..KMMYYMMGMMMK..",
        "..KMMMMMMMMMMK..",
        "...KKKKKKKKKK...",
        "................",
        "................",
    ),
    "mine_sign": (
        "................",
        "...KKKKKKKKKK...",
        "..KNNNNNNNNNNK..",
        ".KNNYYYYYYYYNNK.",
        ".KNNYKKKKKKYNNK.",
        ".KNNYYYYYYYYNNK.",
        "..KNNNNNNNNNNK..",
        "...KKKKKKKKKK...",
        "......KNNK......",
        "......KNNK......",
        "......KNNK......",
        "......KNNK......",
        ".....KNNNNK.....",
        "....KNNNNNNK....",
        "................",
        "................",
    ),
    "pipe_stack": (
        "................",
        ".KKKKKKKKKKKKK..",
        "KgggggggggggggK.",
        "KggEEEEEEEEgggK.",
        ".KKKKKKKKKKKKK..",
        "................",
        "..KKKKKKKKKKKKK.",
        ".KgggggggggggggK",
        ".KgggEEEEEEEEggK",
        "..KKKKKKKKKKKKK.",
        "................",
        ".KKKKKKKKKKKKK..",
        "KgggggggggggggK.",
        "KggEEEEEEEEgggK.",
        ".KKKKKKKKKKKKK..",
        "................",
    ),
    "beacon": (
        "................",
        "......KYYK......",
        ".....KYYYYK.....",
        "....KYYWWYYK....",
        ".....KYYYYK.....",
        "......KYYK......",
        ".......KK.......",
        "......KMMK......",
        ".....KMMMMK.....",
        ".....KMMMMK.....",
        "....KMMMMMMK....",
        "...KMMCCCCMMK...",
        "..KMMMMMMMMMMK..",
        "..KKKKKKKKKKKK..",
        "................",
        "................",
    ),
    "warning_post": (
        "................",
        ".......KK.......",
        "......KAAK......",
        ".....KAWWAK.....",
        ".....KAAAAK.....",
        "......KAAK......",
        ".......KK.......",
        ".......KK.......",
        "......KMMK......",
        ".....KMMMK......",
        "......KMMK......",
        ".....KMMMK......",
        "....KMMMMK......",
        "...KKKKKKKK.....",
        "................",
        "................",
    ),
    "mushroom": (
        "................",
        "................",
        ".....KKKKKK.....",
        "...KKAAAAAAKK...",
        "..KAAWWAAWWAAK..",
        ".KAAAAAAAAAAAAK.",
        ".KAAAtttttAAAAK.",
        "..KKAAAAAAAKK...",
        ".....KSSSK......",
        ".....KSSSK......",
        "....KSSSSSK.....",
        "...KSSSSSSSK....",
        "...KKKKKKKKK....",
        "................",
        "................",
        "................",
    ),
    "hammer_marker": (
        "................",
        "....KKKKKKKK....",
        "...KMMMMMMMMK...",
        "..KMMMMMMMMMMK..",
        "..KKKKKMMKKKKK..",
        "......KMMK......",
        "......KMMK......",
        "......KMMK......",
        "......KMMK......",
        ".....KAAAAK.....",
        "....KAAWWAAK....",
        "...KAAAAAAAAK...",
        "....KKKKKKKK....",
        "................",
        "................",
        "................",
    ),
    "zapper": (
        "................",
        "....KK....KK....",
        "...KCCK..KCCK...",
        "..KCCCCKKCCCCK..",
        "...KCCCCCCCCK...",
        "....KCCCCCCK....",
        ".....KYYYYK.....",
        "....KYYYYYYK....",
        "...KYYYYYYYYK...",
        "....KYYYYYYK....",
        ".....KCCCCK.....",
        "....KCCKKCCK....",
        "...KCCK..KCCK...",
        "....KK....KK....",
        "................",
        "................",
    ),
    "vacuum": (
        "................",
        "..KKKKKKKKKKKK..",
        ".KMMMMMMMMMMMMK.",
        "KMMMMKKKKKKMMMMK",
        "KMMMKCCCCCCKMMMK",
        "KMMKCCKKKKCCKMMK",
        "KMMKCCK..KCCKMMK",
        "KMMKCCK..KCCKMMK",
        "KMMKCCKKKKCCKMMK",
        "KMMMKCCCCCCKMMMK",
        "KMMMMKKKKKKMMMMK",
        ".KMMMMMMMMMMMMK.",
        "..KKKKKKKKKKKK..",
        "....KMMKKMMK....",
        "................",
        "................",
    ),
    "sparkle": (
        "................",
        ".......W........",
        ".......W........",
        ".......Y........",
        "....W..Y..W.....",
        ".....YYYYY......",
        "....WYYYYYW.....",
        "...YYYYYYYYY....",
        "....WYYYYYW.....",
        ".....YYYYY......",
        "....W..Y..W.....",
        ".......Y........",
        ".......W........",
        ".......W........",
        "................",
        "................",
    ),
    "poof": (
        "................",
        "....KMMK........",
        "..KMMMMMMK......",
        ".KMMwwMMMMK.....",
        "KMMwwMMwwMMK....",
        "KMMMMMMMMMMK....",
        ".KMMwwMMMMK.....",
        "..KMMMMMMK......",
        "....KMMK..KMMK..",
        ".........KMMMMK.",
        "..........KMMK..",
        "................",
        "................",
        "................",
        "................",
        "................",
    ),
}


FONT_5X7: Dict[str, Tuple[str, ...]] = {
    " ": ("00000", "00000", "00000", "00000", "00000", "00000", "00000"),
    "0": ("01110", "10001", "10011", "10101", "11001", "10001", "01110"),
    "1": ("00100", "01100", "00100", "00100", "00100", "00100", "01110"),
    "2": ("01110", "10001", "00001", "00010", "00100", "01000", "11111"),
    "3": ("11110", "00001", "00001", "01110", "00001", "00001", "11110"),
    "4": ("00010", "00110", "01010", "10010", "11111", "00010", "00010"),
    "5": ("11111", "10000", "10000", "11110", "00001", "00001", "11110"),
    "6": ("01110", "10000", "10000", "11110", "10001", "10001", "01110"),
    "7": ("11111", "00001", "00010", "00100", "01000", "01000", "01000"),
    "8": ("01110", "10001", "10001", "01110", "10001", "10001", "01110"),
    "9": ("01110", "10001", "10001", "01111", "00001", "00001", "01110"),
    "A": ("01110", "10001", "10001", "11111", "10001", "10001", "10001"),
    "B": ("11110", "10001", "10001", "11110", "10001", "10001", "11110"),
    "C": ("01111", "10000", "10000", "10000", "10000", "10000", "01111"),
    "D": ("11110", "10001", "10001", "10001", "10001", "10001", "11110"),
    "E": ("11111", "10000", "10000", "11110", "10000", "10000", "11111"),
    "F": ("11111", "10000", "10000", "11110", "10000", "10000", "10000"),
    "G": ("01111", "10000", "10000", "10011", "10001", "10001", "01110"),
    "H": ("10001", "10001", "10001", "11111", "10001", "10001", "10001"),
    "I": ("01110", "00100", "00100", "00100", "00100", "00100", "01110"),
    "J": ("00111", "00010", "00010", "00010", "10010", "10010", "01100"),
    "K": ("10001", "10010", "10100", "11000", "10100", "10010", "10001"),
    "L": ("10000", "10000", "10000", "10000", "10000", "10000", "11111"),
    "M": ("10001", "11011", "10101", "10101", "10001", "10001", "10001"),
    "N": ("10001", "11001", "10101", "10011", "10001", "10001", "10001"),
    "O": ("01110", "10001", "10001", "10001", "10001", "10001", "01110"),
    "P": ("11110", "10001", "10001", "11110", "10000", "10000", "10000"),
    "Q": ("01110", "10001", "10001", "10001", "10101", "10010", "01101"),
    "R": ("11110", "10001", "10001", "11110", "10100", "10010", "10001"),
    "S": ("01111", "10000", "10000", "01110", "00001", "00001", "11110"),
    "T": ("11111", "00100", "00100", "00100", "00100", "00100", "00100"),
    "U": ("10001", "10001", "10001", "10001", "10001", "10001", "01110"),
    "V": ("10001", "10001", "10001", "10001", "10001", "01010", "00100"),
    "W": ("10001", "10001", "10001", "10101", "10101", "10101", "01010"),
    "X": ("10001", "10001", "01010", "00100", "01010", "10001", "10001"),
    "Y": ("10001", "10001", "01010", "00100", "00100", "00100", "00100"),
    "Z": ("11111", "00001", "00010", "00100", "01000", "10000", "11111"),
    "$": ("00100", "01111", "10100", "01110", "00101", "11110", "00100"),
    "/": ("00001", "00010", "00010", "00100", "01000", "01000", "10000"),
    "-": ("00000", "00000", "00000", "11111", "00000", "00000", "00000"),
    ":": ("00000", "00100", "00100", "00000", "00100", "00100", "00000"),
    ".": ("00000", "00000", "00000", "00000", "00000", "00100", "00100"),
}


class CrystalCavesArt:
    """Cached pixel-art sprites and tiny DOS-style text."""

    def __init__(self) -> None:
        self._sprite_cache: Dict[Tuple[str, int, bool], pygame.Surface] = {}
        self._text_cache: Dict[Tuple[str, Color, int], pygame.Surface] = {}

    def sprite(self, name: str, scale: int = 2, flip_x: bool = False) -> pygame.Surface:
        key = (name, scale, flip_x)
        cached = self._sprite_cache.get(key)
        if cached is not None:
            return cached

        rows = SPRITES[name]
        width = max(len(row) for row in rows)
        surface = pygame.Surface((width * scale, len(rows) * scale), pygame.SRCALPHA)
        for row_idx, row in enumerate(rows):
            for col_idx, token in enumerate(row):
                if token == ".":
                    continue
                color = EGA.get(token, EGA["K"])
                pygame.draw.rect(
                    surface,
                    color,
                    (col_idx * scale, row_idx * scale, scale, scale),
                )

        if flip_x:
            surface = pygame.transform.flip(surface, True, False)
        self._sprite_cache[key] = surface
        return surface

    def draw_sprite(
        self,
        screen: pygame.Surface,
        name: str,
        x: int,
        y: int,
        scale: int = 2,
        flip_x: bool = False,
    ) -> None:
        screen.blit(self.sprite(name, scale=scale, flip_x=flip_x), (x, y))

    def text(self, text: str, color: Color, scale: int = 2) -> pygame.Surface:
        normalized = text.upper()
        key = (normalized, color, scale)
        cached = self._text_cache.get(key)
        if cached is not None:
            return cached

        glyph_w = 5 * scale
        glyph_h = 7 * scale
        spacing = scale
        width = max(1, len(normalized) * (glyph_w + spacing) - spacing)
        surface = pygame.Surface((width, glyph_h), pygame.SRCALPHA)

        cursor_x = 0
        for char in normalized:
            rows = FONT_5X7.get(char, FONT_5X7[" "])
            for row_idx, row in enumerate(rows):
                for col_idx, bit in enumerate(row):
                    if bit == "1":
                        pygame.draw.rect(
                            surface,
                            color,
                            (
                                cursor_x + col_idx * scale,
                                row_idx * scale,
                                scale,
                                scale,
                            ),
                        )
            cursor_x += glyph_w + spacing

        self._text_cache[key] = surface
        return surface

    def draw_text(
        self,
        screen: pygame.Surface,
        text: str,
        x: int,
        y: int,
        color: Color,
        scale: int = 2,
        shadow: bool = True,
    ) -> None:
        if shadow:
            screen.blit(self.text(text, EGA["K"], scale), (x + scale, y + scale))
        screen.blit(self.text(text, color, scale), (x, y))
