sonar.projectKey=jtn0123_NN-Game1
sonar.organization=jtn0123ismysonar

sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/node_modules/**,**/dist/**,**/.venv/**
sonar.test.inclusions=**/test_*.py,**/tests/**

sonar.python.version=3.11,3.12
